import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { domainInput, botPermissions } = await req.json();

    if (!domainInput || typeof domainInput !== 'string') {
      return NextResponse.json({ error: 'Domain is required' }, { status: 400 });
    }

    let domain = domainInput.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/.*$/, '');
    const robotsUrl = `https://${domain}/robots.txt`;

    let rawRobotsTxt = '';
    let isReachable = false;
    let botStatus: Record<string, boolean> = {
      GPTBot: true,
      'ChatGPT-User': true,
      ClaudeBot: true,
      PerplexityBot: true,
      Bytespider: true,
      'Google-Extended': true,
    };

    try {
      const res = await fetch(robotsUrl, {
        headers: { 'User-Agent': 'Mozilla/5.0' },
        next: { revalidate: 3600 },
      });

      if (res.ok) {
        rawRobotsTxt = await res.text();
        isReachable = true;

        // Check disallow rules
        const lowerRobots = rawRobotsTxt.toLowerCase();
        if (lowerRobots.includes('user-agent: gptbot') && lowerRobots.includes('disallow: /')) botStatus.GPTBot = false;
        if (lowerRobots.includes('user-agent: claudebot') && lowerRobots.includes('disallow: /')) botStatus.ClaudeBot = false;
        if (lowerRobots.includes('user-agent: perplexitybot') && lowerRobots.includes('disallow: /')) botStatus.PerplexityBot = false;
        if (lowerRobots.includes('user-agent: bytespider') && lowerRobots.includes('disallow: /')) botStatus.Bytespider = false;
      }
    } catch (err) {
      console.warn('Robots fetch warning:', err);
    }

    // Generate optimized robots.txt snippet based on user rules or active status
    const rulesToApply = botPermissions || botStatus;

    let generatedRobotsTxt = `# Optimized AI Web Crawler Configuration for ${domain}
# Generated by TangentCore AI Access Guardian

User-agent: *
Allow: /

# OpenAI ChatGPT & Search Crawlers
User-agent: GPTBot
${rulesToApply.GPTBot ? 'Allow: /' : 'Disallow: /'}

User-agent: ChatGPT-User
${rulesToApply['ChatGPT-User'] ? 'Allow: /' : 'Disallow: /'}

# Anthropic Claude Crawlers
User-agent: ClaudeBot
${rulesToApply.ClaudeBot ? 'Allow: /' : 'Disallow: /'}

# Perplexity Search Crawlers
User-agent: PerplexityBot
${rulesToApply.PerplexityBot ? 'Allow: /' : 'Disallow: /'}

# ByteDance & DeepSeek Crawlers
User-agent: Bytespider
${rulesToApply.Bytespider ? 'Allow: /' : 'Disallow: /'}

# Google AI Gemini & Vertex Crawlers
User-agent: Google-Extended
${rulesToApply['Google-Extended'] ? 'Allow: /' : 'Disallow: /'}

Sitemap: https://${domain}/sitemap.xml
`;

    return NextResponse.json({
      success: true,
      data: {
        domain,
        isReachable,
        botStatus,
        generatedRobotsTxt,
      },
    });
  } catch (err: any) {
    console.error('Robots API Error:', err);
    return NextResponse.json({ error: 'Failed to inspect robots.txt' }, { status: 500 });
  }
}
